# Generated by Django 3.0.6 on 2020-05-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='preço')),
                ('photo', models.ImageField(upload_to='', verbose_name='foto')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
            ],
        ),
    ]
